includes:
  - configs/s2ef/MD22/datasets/Ac-Ala3-NHMe/base.yml
  - configs/s2ef/MD22/EScAIP/base/L6_H8_512_.yml
  - configs/slurm/regular.yml

model:
  avg_num_nodes: 42
  max_num_nodes_per_batch: 48
optim:
  batch_size: 48
  eval_batch_size: 32
  eval_every: 500
  max_epochs: 10000
  lr_initial: 0.00004

  scheduler_params:
    lr_min_factor: 0.75
