includes:
  - configs/s2ef/MD22/datasets/double-walled_nanotube/base.yml
  - configs/s2ef/MD22/EScAIP/base/L6_H8_256_.yml
  - configs/slurm/regular.yml

model:
  avg_num_nodes: 370
  max_num_nodes_per_batch: 384
optim:
  batch_size: 4
  eval_batch_size: 2
  eval_every: 500
  max_epochs: 10000
  lr_initial: 0.00004
