trainer: ocp

dataset:
  train:
    format: lmdb
    # src: /pscratch/sd/e/ericqu/OC20/s2ef/2M/train/
    src: /datasets01/open_catalyst/oc20/082422/struct_to_energy_forces/train/s2efall_md38M/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -0.7554450631141663
          stdev: 2.887317180633545
        forces:
          mean: 0
          stdev: 2.887317180633545
  val:
    # src: /pscratch/sd/e/ericqu/OC20/s2ef/all/val_12k_sub/
    src: /datasets01/open_catalyst/oc20/082422/struct_to_energy_forces/val/id_30k/

logger: wandb

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 2
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
